### ISSUE TITLE
CTAS queries down work

### ISSUE THREAD

**Issue by jamesp26** [ghdna/athena-express#10]
CTAS queries (https://docs.aws.amazon.com/athena/latest/ug/ctas-examples.html ) don't output data to S3 and fail when calling the 'query' function.  'Query' fails if there is no S3 file to pick the data up from. 

I'm hardcoding my way around it for now, but wondered if it would be possible to add one of the 2 solutions:

1. Add a property called getResults (default to true) to the athenaExpressConfig.  If false, dont run the getQueryResultsFromS3 function.

2. Add a new function called execute, which does the same as query except doesn't look for results. This is kind of how ORM's work, and would be an elegant way out running DDL statements in AthenaExpress.

Ta!

**Comment by bkcompton** [comment]
I ran into this same issue. I resolved it by adding an additional parameter to the query method:
`async query(query, ignoreResultsFile = false) { ...`

This gives me the flexibility to ignore any results file in the future although I don't really have a concrete use case for it at this time. 

Side Note: I added a few additional configuration points as well as did some code cleanup. I plan to add a PR shortly with the outlined improvements.

**Comment by ghdna** [comment]
This is a good feature to add. I'm looking into it. Thanks for raising it.

**Comment by bkcompton** [comment]
Ghdna,

I have a feature branch that I would like to raise a PR for. Would it it be possible for you to allow me the permission to create a feature branch?

**Comment by ghdna** [comment]
I would like to approach this slightly differently. The purpose of creating this library was to make it simpler to use Athena, which means taking the onus away from user for a lot of the trivial decisions: Such as whether an Athena query stores results in S3 or not for CTAS queries. This should be handled by us (athena-express) instead of determined by the user. I'm looking into ways of detecting this based on the query itself. That way a user shouldn't care of changing (and knowing what to change on) the config params based on the query to be run.

**Comment by bkcompton** [comment]
I think that is the right approach.

**Comment by ghdna** [comment]
Update: Dedicated my Sunday to this and found a _slightly less elegant_ way to detect CTAS queries before deciding whether to fetch data from S3 or not. But the advantage here is that it doesn't require the user to do anything different when executing queries. Thank you @bkcompton & @jamesp26 from bringing this issue up.
