### ISSUE TITLE
Need help!!! It seems that this package can not be used in React.js

### ISSUE THREAD

**Issue by simon-zhangmuye** [ghdna/athena-express#62]
When you call it from a standalone js file, it works.
Then you try to move it in React, it cannot find Athena Object.
Can anyone fix this problem?

![image](https://user-images.githubusercontent.com/10706610/116796973-184ffe00-ab24-11eb-95a3-fed4b5aa5ebb.png)
![image](https://user-images.githubusercontent.com/10706610/116796996-577e4f00-ab24-11eb-880f-4178a3493427.png)

**Comment by simon-zhangmuye** [comment]
Now it does not work in standalone js file

**Comment by ghdna** [comment]
Trying to understand your use case here. 
A react app is meant for browsers (i.e. anyone on the internet can read the contents of the react app) and hence its usually not a good idea to embed middleware like athena-express directly within the react app. Since invoking athena-express, requires passing an authenticated aws object, you risk exposing your aws credentials through the react app on the internet. 

What you can do instead is separate out the 2 pieces: (1) AthenaExpress that is hosted on a server or FaaS (e.g. on an EC2 or Lambda if using AWS) and (2) Your react app that is hosted on a separate server (another EC2 or S3 if using AWS). And then you connect the 2 using APIs.

Happy to chat more and help you through this.

**Comment by simon-zhangmuye** [comment]
I can use AWS amplify to deploy the source code to AWS. So there is no risk of exposing my aws credentials.

**Comment by simon-zhangmuye** [comment]
I just get confused. Why there is no Athena object in a browser but works in a standalone js file?

**Comment by simon-zhangmuye** [comment]
I just get confused. Why there is no Athena object in a browser but works in a standalone js file?

**Comment by simon-zhangmuye** [comment]
Can you fix this problem and let me to use athena express in React project?

**Comment by simon-zhangmuye** [comment]
Athena does not support browser access.

> Trying to understand your use case here.
> A react app is meant for browsers (i.e. anyone on the internet can read the contents of the react app) and hence its usually not a good idea to embed middleware like athena-express directly within the react app. Since invoking athena-express, requires passing an authenticated aws object, you risk exposing your aws credentials through the react app on the internet.
> 
> What you can do instead is separate out the 2 pieces: (1) AthenaExpress that is hosted on a server or FaaS (e.g. on an EC2 or Lambda if using AWS) and (2) Your react app that is hosted on a separate server (another EC2 or S3 if using AWS). And then you connect the 2 using APIs.
> 
> Happy to chat more and help you through this.
