### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarthRevanXX** [ghdna/athena-express#7]
Trying to import "athena-express" and have an error: **Could not find a declaration file for module 'athena-express'**
https://stackoverflow.com/questions/56558127/module-not-found-cant-resolve-readline?noredirect=1#comment99696483_56558127

**Comment by ghdna** [comment]
The readline issue could be resolved by npm installing readline. This seems to be a common issue with create-react-app. See [this](https://github.com/GoogleChrome/puppeteer/issues/1965) and [this](https://github.com/facebook/create-react-app/issues/3543). Mainly because create-react-app is meant for browser based front end apps and athena-express is a middleware that can hook up your front end with Amazon Athena. If you install athena-express on front end, you will end up exposing your aws object that contains your secret key & access key. 

Your best bet is to create a simple node.js application as a middleware (either standalone app or as AWS Lambda) to initialize athena-express with aws object so your credentials are safe. Then you can invoke athena-express as an API from your browser react app. See the architecture diagram and code samples on the readme.

**Comment by DarthRevanXX** [comment]
Ok, thank you very much, fixed
